version: '3.7'
services: 
    database:
        build: ./database
        ports: 
            - 3300:3300
    backend:
        build: ./backend_withus
        ports: 
            - 8000:8000
        depends_on: 
            - database
    frontend:
        build: ./frontend_withus
        ports:
            - 3000:3000
        volumes:
            - ./frontend_withus:/usr/src/app